[package]
name = "render-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
typst = "0.13"
typst-pdf = "0.13"
comemo = "0.5"
ecow = "0.2"
fontdb = "0.23"
chrono = { version = "0.4", features = ["std"] }
