[package]
name = "render-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
typst = "0.13"
typst-pdf = "0.13"
typst-svg = "0.13"
thiserror = "1.0.69"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
jsonschema = "0.33.0"
