[package]
name = "typst-wrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
typst = "0.13"
typst-pdf = "0.13"
typst-svg = "0.13"
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1.0.69"
comemo = "0.5"